name: Deploy Prefect flow

on:
  push:
    branches:
      - flow-deploy
      - task-develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obtener código de rama flow-deploy
        run: |
          git fetch origin flow-deploy
          git checkout origin/flow-deploy

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          URL: ${{ secrets.URL }}
        run: |
          pip install -r requirements.txt
          python my_flow.py